# -*- coding: utf-8 -*-
"""activation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wF12v2G7t0FW5EgIITG4YJMdLWDDqwcm
"""

import numpy as np

# All of these need to be able to handle 2D numpy arrays as inputs.

class tanh(object):
    @staticmethod
    def calc(v):
        return np.tanh(v)